import { Annotation } from "@langchain/langgraph";
import { BaseMessage } from "@langchain/core/messages";
import { FunctionCall, Content } from "@google/genai";

// The state for our research agent
export const SearchAgentStateAnnotation = Annotation.Root({
  user_message: Annotation<string>,
  response: Annotation<string | null>({
    default: () => null,
    reducer: (current, update) => update ?? current,
  }),
  search_queries: Annotation<string[]>({
    // New: Queries generated by planner
    default: () => [],
    reducer: (s: string[], a: string[]) => s.concat(a),
  }),
  search_results: Annotation<Array<{ query: string; result: string }>>({
    // New: Results from searches
    default: () => [],
    reducer: (
      s: Array<{ query: string; result: string }>,
      a: Array<{ query: string; result: string }>,
    ) => s.concat(a),
  }),
  messages: Annotation<Array<BaseMessage>>({
    default: () => [],
    reducer: (s: Array<BaseMessage>, a: Array<BaseMessage>) => s.concat(a),
  }),
  function_calls: Annotation<Array<FunctionCall>>({
    default: () => [],
    reducer: (s: Array<FunctionCall>, a: Array<FunctionCall>) => s.concat(a),
  }),
});

export type SearchAgentState = typeof SearchAgentStateAnnotation.State;
